# spring.application.name=spring-ai-demo
# spring.ai.openai.api-key=${OPENAI_API_KEY}


# Disabilita l'autoconfigurazione di OpenAI
spring.autoconfigure.exclude=org.springframework.ai.model.openai.autoconfigure.OpenAiAudioSpeechAutoConfiguration,org.springframework.ai.model.openai.autoconfigure.OpenAiAutoConfiguration

# spring.ai.chat.client.enabled=false

# Configura Ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2